### ISSUE TITLE
Add link to github on each footer

### ISSUE THREAD

**Issue by modir** [MithrilJS/docs#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Offending URL

https://mithril.js.org/

### Issue description

Please add on each page's footer a link to the github page. Then it is a lot easier to help with the documentation.

**Comment by dead-claudia** [comment]
Fixed in https://github.com/MithrilJS/docs/commit/06cbbdd9e85ef123a3d2a67b68cae312a2fe7b20
