### ISSUE TITLE
Update hyperscript "Avoid statements in view methods" docs for clarity

### ISSUE THREAD

**Issue by elongberg** [MithrilJS/docs#25]
From example [Avoid statements in view methods](https://mithril.js.org/hyperscript.html#avoid-statements-in-view-methods)

> Constructing an virtual DOM tree procedurally can also potentially trigger expensive deoptimizations

The AVOID example proceeds to generate a list using
```javascript
    var list = []
    for (var i = 0; i < vnode.attrs.items.length; i++) {
	list.push(m("li", vnode.attrs.items[i]))
    }
```
while the PREFER example also generates a list but uses the nicer-looking
```javascript
    vnode.attrs.items.map(function(item) {
	return m("li", item)
    })
```

Unless I am missing something, both examples are functionally identical and have nothing to do with the quoted text. Is there any example that might relate better to the quoted text?

**Comment by dead-claudia** [comment]
This was fixed years ago.
