### ISSUE TITLE
Use a documentation generator software

### ISSUE THREAD

**Issue by modir** [MithrilJS/docs#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Offending URL

https://mithril.js.org/

### Issue description

I already worked on several documentations for open source projects and in helped me to use a software like e.g. https://www.mkdocs.org/ to generate the documentation. A lot of things (e.g. code highlighting, search) is already included  or available as plugins.

I don't know in what direction you want to go but at least write in the README how you want to generate the documentation in the future. (How does the automatic process look like etc.

**Comment by dead-claudia** [comment]
For the foreseeable future, I don't see us switching to anything else. No need to replace what isn't broken. I will document the current local dev process, though, so it's easier for people to get started.

Docs generators aren't really suitable for us, for a couple big reasons:

1. Docs generators focus on methods and functions, which is fantastic for traditional libraries, and some small [embedded DSLs](https://en.wikipedia.org/wiki/Domain-specific_language) can get away with that, but they tend to fall apart for larger embedded DSLs like ours.
2. The core API is relatively small, but the amount of detail we go into is exceptionally high. There would be so much documentation in code comments, it'd make the core code itself difficult to follow.

**Comment by dead-claudia** [comment]
Added the contributing guide in https://github.com/MithrilJS/docs/commit/099898e783c55ab766b572b5495b14eab6f104ee
