### ISSUE TITLE
Got an error after creating an issue here

### ISSUE THREAD

**Issue by modir** [MithrilJS/docs#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Offending URL

https://github.com/MithrilJS/docs/

### Issue description

I got this error message now as an email for each issue I created:

Notify triage on issue create: All jobs have failed
Notify triage on issue create / reject / notify
Failed in 3 seconds

**Comment by dead-claudia** [comment]
Sorry, didn't realize you were getting emails over that. I'll disable the action here in the repo to prevent more email spam. It's ultimately blocked on a known issue we're tracking: https://github.com/MithrilJS/infra/issues/25. I'm blocked on what appears to be a GitHub backend bug.

Closing as that's the main tracking issue.
